#!/sw/bin/python

import sys
import json

def create_jid_html(jobs):

    all_plain_jids = ""
    all_jids_w_link = ""
    all_freestyle_match = ""
    all_links = ""

    index = 1

    for job in JOBS:

        jid = str(job['jid'])
        link = "http://tractor-engine/tv/#jid={}".format(jid)
        href_jids = """<a href="{}">{}</a>""".format(link, jid)
        href_link = """<a href="{}">{}</a>""".format(link, link)

        if index == len(JOBS):
            all_plain_jids += "{}".format(jid)
            all_jids_w_link += "{}".format(href_jids)
            all_freestyle_match += "jid={}".format(jid)
            all_links += "{}".format(href_link)
        else:
            all_plain_jids += "{} | ".format(jid)
            all_jids_w_link += "{} | ".format(href_jids)
            all_freestyle_match += "jid={} or ".format(jid)
            all_links += "{} </br>".format(href_link)

        index += 1

    stats_html = """
            <p class="title-text"><u>Plain Job ID(s)</u>:</p>
            <p class="information">
                {all_plain_jids}
            </p>
            
            <p class="title-text"><u>Job ID(s) with Link</u>:</p>
            <p class="information">
                {all_jids_w_link}   
            </p>
            
            <p class="title-text"><u>Job ID(s) Freestyle Match</u>:</p>
            <p class="information">
                {all_freestyle_match}   
            </p>
            
            <p class="title-text"><u>Job ID(s) Tractor Links</u>:</p>
            <p class="information">
                {all_links}   
            </p>
        """.format(all_plain_jids=all_plain_jids, all_jids_w_link=all_jids_w_link,
                   all_freestyle_match=all_freestyle_match, all_links=all_links)

    return stats_html

def html_formatting(job_i):
    """ This functions contains all the HTML used to create and format the
        window created when the shotgrid_url_getter tool is used.

            Parameters:
                job_i (str): the error message generated by the debug_errors()
                function which is already formatted as HTML to be added as part
                of the main HTML here.
            Returns:
                html (str): the final HTML running the main window.
    """

    html_head_content = """<!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="UTF-8">
                <title>Get Job ID(s)</title>

                <script type='text/javascript'> 
                    window.resizeTo(650, 500);       
                </script>

                <style> 
                    html, body {
                        width: 100%;
                        height: 100%; 
                        margin: 1;
                        background: #181A1B;
                        font-family: gill sans, sans-serif;
                    }
                    body {
                        overflow-x: hidden;
                        overflow-y: visible;
                    }
                    body::after {
                        content: '';
                        display: block;   
                        height: 30px; /* Set same as footer's height */
                    }                                
                    h3 {
                        font-size: 35px;
                        color: white;
                    }
                    .title-text {
                        font-weight: bold;
                        text-align:left;
                        font-size: 16px;
                        padding-left: 35px;
                        color: white;
                    }
                    .information {
                        text-align:left;
                        font-size: 14px;
                        padding-right: 50px;
                        padding-left: 35px;
                        color: white;
                   }
                   /* Scrollbar */
                    ::-webkit-scrollbar {
                        width: 10px;
                    }
                    ::-webkit-scrollbar-track {
                        box-shadow: inset 0 0 5px grey;
                        border-radius: 10px;
                    }
                    ::-webkit-scrollbar-thumb {
                        background: #575e62;
                        border-radius: 10px;
                    }
                    ::-webkit-scrollbar-corner {
                        background: rgba(0,0,0,0);
                    }
                </style>
            </head>"""

    body = """<body link="#3790f9" alink="#017bf5" vlink="#3790f9">
                    <main>
                        <h3 align="center">
                            <u>Formatted Job IDs</u>
                        </h3>

                        <br/>

                        <section id="get_jids">{x}</section>

                    </main>
                </body>
        </html> 
        """.format(x=job_i)

    html = html_head_content + body

    return html

if __name__ == "__main__":

    # Take in the data from Tractor, load as json.
    SYS_IN_JSON = sys.stdin.read()
    JOBS = json.loads(SYS_IN_JSON)
    sys.stdout.write("Content-type:text/html\r\n\r\n")

    jid_html = create_jid_html(JOBS)
    full_html = html_formatting(jid_html)
    sys.stdout.write(full_html)
